title: GitHub Pages with Jerkyll example
author: osa0508-cyber
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I talk about GitHub and I use Github Paages to show that you can do it too.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
